- name: Demo of vars on Play level
  hosts: all
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print Variable Value
      debug:
        msg: Hello {{ URL_PLAY }}
    - name: Print Variable agin
      debug:
        msg: Bye {{ URL_PLAY }}
    - name: varibale in task level
      debug:
        msg: Hello {{ URL_TASK1 }}
      vars:
        URL_TASK1: task1.example.com
    - name: varibale in task level
      debug:
        msg: Hello {{ URL_PLAY }}