- name: conditions
  hosts: all
  become: yes
  vars:
    A: 100
    INSTALL: true
  tasks:
    - name: Condition on strings
      debug:
        msg: Condition on strings
      when: APP == "frontend"
    - name: Condition on number
      debug:
        msg: Condition on number
      #when: A == 101
      #when: A > 50
      when: A != 50
    - name:  Condition on boolean
      debug:
        msg: Condition on boolean
      when: INSTALL | bool