- name: conditions
  hosts: all
  become: yes
  vars:
    A: 100
  tasks:
    - name: Condition on strings
      debug:
        msg: Condition on strings
      when: APP == "frontend"
    - name: Condition on number
      debug:
        msg: Condition on num
      when: A == 101