- name: roboshop
  hosts: all
  become: yes
  tasks:
    - name: install nginx frontend
      import_role:
        name: frontend
    - name: install mongodb
        import_role:
          name: frontend
