- name: roboshop
  hosts: all
  become: yes
  tasks:
    - name: install nginx frontend
      import_role:
        name: frontend
      when: APP=="frontend"
    - name: install mongodb frontend
      import_role:
          name: mangodb
      when: APP=="mangodb"
