- name: Install the latest version of Nginx
  yum:
    name: nginx
    state: latest
- name: download from Git hub
  include_role:
    name: common
    tasks_from: download-github

#- name: Remove file (delete file)
 # file:
 #   path: /usr/share/nginx/html
 #   state: absent