- name: Copy mongodb repo file
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
- name: Install mongoDB
  yum:
    name: mongodb-org
    state: installed
- name: replace line
  lineinfile:
      path: /etc/mongod.conf
      regexp: '^(.*)bindIp:(.*)$'
      line: 'bindIp: 0.0.0.0'
      backrefs: yes