- name: catalogue config
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: installed
- name: create user
  user:
    name: roboshop
- name: download from Git hub
  include_role:
    name: common
    tasks_from: download-github