- name: Download file
  get_url:
    url: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp/{{COMPONENT}}.zip
- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /tmp
    remote_src: yes

- name: file transfer from one place to another app location
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
  remote_src: yes
 # when: APP=="frontend"